services:
  - type: web
    name: hippodrome-solver
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd frontend_explorer && gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
